### ISSUE TITLE
Instrument block_on

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/console#106]
The task used for `block_on`, both when using `#[tokio::main]` and when using `Runtime::block_on` or `Handle::block_on`, isn't instrumented and thus shown in the Console. It'd be good to do so.

We could either consider it a _form_ of spawn, thus using `runtime::spawn` for the span and setting the `kind=block_on` or `kind=main`. Or, we could call it `runtime::block_on`, but then we'd need to add support to the Console to look for that new span.

**Comment by hawkw** [comment]
> We could either consider it a _form_ of spawn, thus using `runtime::spawn` for the span and setting the `kind=block_on` or `kind=main`. Or, we could call it `runtime::block_on`, but then we'd need to add support to the Console to look for that new span.

hmm...in retrospect, perhaps a better name would have been `runtime::task`, rather than `runtime::spawn`. i think it's a little more reasonable to think of `block_on` as being a "task" than as being a "spawn". but, i dunno if it's worth the effort of renaming everything _again_ (and adding another set of backwards compatibility names for in case people are using old tokio versions) just to make it the _most_ correct possible.

honestly, i would _probably_ just add a span in Tokio with the `runtime::spawn` name and `kind=block_on`...that seems like the lowest effort and doesn't require new code in the console. we could then consider renaming the target from `spawn` to `task` in a follow-up?
