### ISSUE TITLE
Consider option to disable expiring of stopped tasks

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/console#108]
In applications with short-lived tasks, it may be desirable to always see all finished tasks. Or at least be able to specify as such when running the `console` app. (Does this seem like a feature anyone else would want?)

To do this, we would add another command line option to the console in `console/src/config.rs`, set the value in `console/src/tasks.rs`, and check it before calling `retain`.

**Comment by hawkw** [comment]
I think adding an option to configure this would be fine...as long as the docs make it extremely obvious to users that this is essentially creating an (intentional) memory leak. I'd like to avoid a situation where people go "oh, of course I'd want as much data as possible", enable it in a long-running process, and then are surprised when their program gets OOM killed.

In the longer term, we might want to think about persisting expired tasks to disk (similar to the JSON recording we're already doing). That way, we get them out of memory once they're no longer relevant, and if someone connects to the application and requests the data, we can read that file, parse it, and send the expired tasks.

**Comment by seanmonstar** [comment]
> In the longer term, we might want to think about persisting expired tasks to disk (similar to the JSON recording we're already doing). 

Yes 1000%. I've thought that as well, when I was working out recording.

But in this issue, I'm not talking about an option for the subscriber, but rather for the `console` CLI app. I don't imagine people opening that up and leaving it to run forever... Though I suppose people could. Perhaps instead the option could be to extend how long the stopped task is retained, instead of just keeping them indefinitely.

**Comment by hawkw** [comment]
> But in this issue, I'm not talking about an option for the subscriber, but rather for the `console` CLI app. I don't imagine people

Oh, my bad --- I completely misread the issue. Yeah, that seems like a good idea.

**Comment by seanmonstar** [comment]
I think having the duration be an CLI arg makes sense. We have this duration parsing stuff in the subscriber, it'd be cool to be able to share it... But having yet another crate that both can depend on seems annoying...
