### ISSUE TITLE
console: `Polls` are stripped when a value is greater than 99999

### ISSUE THREAD

**Issue by hatoo** [tokio-rs/console#134]
![image](https://user-images.githubusercontent.com/1667746/132940640-e91cfcf0-4321-42e4-9e6b-bf9397139dfe.png)

console doesn't show `Polls` properly when the value is greater than 99999.

**Comment by seanmonstar** [comment]
Nice catch. The fix is likely simple, just need to update the table constraint to be bigger if numbers are wider than 5 characters.

Or I suppose we could at a certain point turn the number into a float, like `14.3k`...

**Comment by hawkw** [comment]
The easiest thing is definitely just to replace the fixed 5-character constraint with the `Width` type to dynamically calculate a constraint, the way we do for other variable-length fields. We would want to make this line:
https://github.com/tokio-rs/console/blob/7231a33268d409e4188c49b91ae8fc77c2889df6/console/src/view/tasks.rs#L157
look more like this line:
https://github.com/tokio-rs/console/blob/7231a33268d409e4188c49b91ae8fc77c2889df6/console/src/view/tasks.rs#L158
and make this line:
https://github.com/tokio-rs/console/blob/7231a33268d409e4188c49b91ae8fc77c2889df6/console/src/view/tasks.rs#L274
look more like this line:
https://github.com/tokio-rs/console/blob/7231a33268d409e4188c49b91ae8fc77c2889df6/console/src/view/tasks.rs#L275

(of course, we would also need to actually construct a new `Width` type and pass it around and so on). @hatoo, if you're interested in fixing this, that should be pretty straightforward.

@seanmonstar's alternative suggestion,
> Or I suppose we could at a certain point turn the number into a float, like `14.3k`...

might be nicer in the long run, especially if we want to instrument programs where tasks see really huge numbers of polls. This might take a bit more effort than simply updating this code to use the `Width` type, but it would save a few characters if tasks are polled a _lot_. Truncating like that is probably fine to do, since the exact number of polls would still be available on that task's details view --- if the user really wants to look at the ones place for a task that has been polled 20k times, that data is still there.  But most of the time, once you have that many polls, you probably don't care a ton about the ones place anymore.
