### ISSUE TITLE
subscriber: consider making `with_default_env` the default

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/console#205]
> do we _really_ need an explicit `with_default_env`? would it be better to just have `Builder::default()` read the default env variables if they're set? i could be convinced either way on that one.
>
> _Originally posted by @hawkw in https://github.com/tokio-rs/console/pull/195#pullrequestreview-833252597_

**Comment by hawkw** [comment]
cc @pnkfelix @seanmonstar what do you think about this? if we're going to change it, it might be good to do before 0.1 so we don't have to immediately deprecate `with_default_env`...

**Comment by pnkfelix** [comment]
I have a slight bias to leaving things the way they are, because I'm not confident that it is a good idea to have *no way* to turn off the code path that accesses the environment variables... 
 * Well, I guess one can always call every builder method explicitly to side-step those concerns, so that every setting gets established in the code, overwriting the values derived from the environment.
 * Or we could add a new constructor method that explicitly says it doesn't inspect the environment, i.e. essentially recreate today's `Builder::default()` but with a name that more directly reflects its role...
 
So I'm not attempting to present this as a particularly solid argument for the status quo. Its mostly a gut feeling.

**Comment by hawkw** [comment]
Cool, let's not change this, then.
