### ISSUE TITLE
Reduce the number of digits shown in UI

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/console#224]
It probably doesn't make much sense to include fractions in the numbers displayed in the UI.

ref: https://news.ycombinator.com/item?id=29596537

**Comment by hawkw** [comment]
I think we probably _do_ want one or two fractional digits, at least for larger units like seconds, but definitely not 4 like we have currently.

**Comment by pnkfelix** [comment]
Can we just vary the fraction so that we aim for 3 significant figures total when the non-fractional part is less than 1000? (And when its >= 1000, then the fractional part should be hidden.)

Is that the wrong way to look at this?

**Comment by hawkw** [comment]
not _directly_ related, but we probably also want to format durations over one or two minutes as minutes + seconds, rather than as a large number of seconds, which it looks like [`std::time::Duration`'s `fmt::Debug` implementation doesn't do](https://doc.rust-lang.org/src/core/time.rs.html#1225-1247). So, at some point, we're definitely going to end up writing our own duration formatter, and we can probably implement significant figures logic there as well?

**Comment by carllerche** [comment]
> I think we probably _do_ want one or two fractional digits, at least for larger units like seconds, but definitely not 4 like we have currently.

Depends... `5m20s` maybe, but 3.245ms... probably not. I think 3ms would make more sense there.
