### ISSUE TITLE
duplicated controls on resource details screen

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/console#258]
It looks like the resource details screen currently has two separate "controls" help sections, one of which is for the details screen and the other of which is for the table:
![image](https://user-images.githubusercontent.com/2796466/148848136-276f41d3-5c7c-4de0-b4c8-382794588e9c.png)

I believe the top one is rendered by the details view, and the lower one is rendered by the table itself.
 
This is _not_ the case for the task details view, because it doesn't include a table element: 
![image](https://user-images.githubusercontent.com/2796466/148848255-4a42b85d-0119-404e-abe1-38aee56575b9.png)

We might want to combine these? Or...maybe it's fine? What do people think?

**Comment by hds** [comment]
This issue is is still valid on `main`.

It is a little bit better. All the controls are now rendered at the top of the resource detail screen. However, the controls for the table of Async Ops is still rendered above that table and need to be removed.

![tokio-console-screenshot-2024-February-11-81427](https://github.com/tokio-rs/console/assets/89589/03964acf-b5a9-403a-9d54-9811a03661ab)

The controls that are rendered at the top of the Async Ops table come from here. This can be removed and then the necessary cleanup performed so that we don't have unused variables hanging around.
https://github.com/tokio-rs/console/blob/45932229fb5aea7a4994a7644bded9baf2776ea8/tokio-console/src/view/async_ops.rs#L237

Hint: There is a `split(area)` which is no longer necessary.

**Comment by devanbenz** [comment]
@hds Thanks for the updates here, could you please go ahead and assign this issue to me :D

**Comment by devanbenz** [comment]
https://github.com/tokio-rs/console/pull/519 this is the PR for this issue :)
