### ISSUE TITLE
The console randomly die with an unwrap

### ISSUE THREAD

**Issue by dzamlo** [tokio-rs/console#266]
The console randomly die after some time. Running with `RUST_LOG=debug`  and `RUST_BACKTRACE=full` produce this log file: [console.txt](https://github.com/tokio-rs/console/files/7924035/console.txt) (I suggest printing the log file in a terminal so you get the colors and other formatting)

## Error
```
called `Result::unwrap()` on an `Err` value: SystemTimeError(836.154µs)
```

## Metadata
|key|value|
|--|--|
|**version**|0.1.1|
|**location**|tokio-console/src/state/async_ops.rs:214:61|

**Comment by zaharidichev** [comment]
I think this is due to the fact that essentially before #238 the subscriber was acting like an actor wrt to state updates and these were all driven by messages. So at the time of publishing an update message on the wire it was the case that this message timestamp will be after any other timestamp that was written into the AsyncOp stats. Since these stats are now shared between the aggregator and the `ConsoleLayer` and guarded by a lock, we can actually observe an `Update.now` timestamp that is before a `Stats.dropped_at` timestamp. We should fix that. Two possible ways of doing that: 

1. Make sure that when publishing an update we take the `now` timestamp after everything else has been converted to proto repr.
2. Handle the case in the console where a timestamp can be after the `Update.now`  one.
