### ISSUE TITLE
Support for platforms where AtomicU64 does not exist

### ISSUE THREAD

**Issue by spacemeowx2** [tokio-rs/console#279]
When cross-compile to mipsel I get this error:

```
$ cross build --release --target mipsel-unknown-linux-musl
...
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
 --> /cargo/registry/src/github.com-1ecc6299db9ec823/console-subscriber-0.1.2/src/stats.rs:8:26
  |
8 |     atomic::{AtomicBool, AtomicU64, AtomicUsize, Ordering::*},
  |                          ^^^^^^^^^
  |                          |
  |                          no `AtomicU64` in `sync::atomic`
  |                          help: a similar name exists in the module: `AtomicU8`
```

See also:

https://doc.rust-lang.org/std/sync/atomic/index.html#portability

**Comment by hawkw** [comment]
Hmm, unfortunately, the `AtomicU64` here is used to store a task ID, which is a 64-bit integer. The counters in the same module already use `AtomicUsize`. In order to record this data correctly, we have to be able to store all 64 bits — using a machine-sized atomic could result in collisions between task IDs.

This means that we can't fix this by just switching the task ID to an `AtomicU64`. Instead, we will need to use an approach where we use a 64-bit atomic on platforms that support them, and fall back to using a mutex on platforms that don't. This introduces a bit of complexity, but it's certainly doable. One option would be to just add a dependency on `crossbeam-util` in order to use its `AtomicCell<T>` type, which implements this behavior. Alternatively, we could do it ourselves with the various platform cfgs Rust exposes...

**Comment by hawkw** [comment]
PR #282 should hopefully fix this (though [I could use some help verifying that](https://github.com/tokio-rs/console/pull/282#issuecomment-1039365688)).
