### ISSUE TITLE
Application works with console in debug but not in release

### ISSUE THREAD

**Issue by rukai** [tokio-rs/console#315]
### What crate(s) in this repo are involved in the problem?

console-subscriber

### What is the issue?

The application I am trying to use the console with displays 0 tasks and all the logs from tracing_subscriber except the error logs are missing.

This is my application running in --release:
![image](https://user-images.githubusercontent.com/5120858/160782572-856591bf-1749-47ef-aa07-0a3704d6c348.png)

This is my application running in debug:
![image](https://user-images.githubusercontent.com/5120858/160782661-f86e6020-9467-4653-a336-56f3a919d52d.png)

### How can the bug be reproduced?

I setup tokio console as per the instructions in the tokio console readme:
https://github.com/rukai/shotover-proxy/commit/f7388d4314f269f47a4139457a186535a296b244

Then I run the application:
```sh
git clone https://github.com/rukai/shotover-proxy
cd shotover-proxy/shotover-proxy
git checkout _drafts/tokio_console
cargo run # this works
cargo run --release # this does not work
```

And attempt to run the tokio console against it:
```sh
git clone https://github.com/tokio-rs/console
cd console
cargo run --release
```

I am raising an issue in case anyone has immediate ideas on what could be going wrong, but i'll try to at least bisect whats causing the console to fail so spectacularly when I get the chance.

### Versions

rukai@memes shotover-proxy$ cargo tree | grep console-
├── console-subscriber v0.1.3
│   ├── console-api v0.1.2

tokio-console is latest git

### Would you like to work on fixing this bug?

If I get the chance i'll look into this further.

**Comment by hawkw** [comment]
Looking at your `Cargo.toml`, I see that the `tracing` crate's `release_max_level_info` feature is enabled: https://github.com/rukai/shotover-proxy/blob/f7388d4314f269f47a4139457a186535a296b244/shotover-proxy/Cargo.toml#L57

This means that all `tracing` diagnostics more verbose than `INFO` are disabled at compile time in release mode. The `tracing` events in Tokio that the console subscriber collects are at the `TRACE` level, so with this feature enabled, those events are not present in release mode.

Try removing `release_max_level_info` from the `tracing` crate's feature flags, and then everything should work.

**Comment by rukai** [comment]
That fixes the issue of the console showing no tasks.
thankyou!

Is it expected that all the stdout logs from tracing_subscriber except the error logs are missing when I use `console_subscriber::init()`?
Because im still getting that issue.
It occurs on both debug and release.

**Comment by hawkw** [comment]
> Is it expected that all the stdout logs from tracing_subscriber except the error logs are missing when I us

[`console_subscriber::init()`](https://docs.rs/console-subscriber/latest/console_subscriber/fn.init.html#) sets the [default `tracing` subscriber](https://docs.rs/tracing/latest/tracing/dispatcher/index.html#setting-the-default-subscriber) for the program. Once the default subscriber is set, it cannot be set again, and attempting to set a new one will return an error. 

It looks like `shotover_proxy::Runner` will internally set a different `tracing` subscriber, with a different configuration: https://github.com/rukai/shotover-proxy/blob/469d3f56d78cc34a6c472dfb090eab59f820054a/shotover-proxy/src/runner.rs#L186-L204

However, because you've added `console_subscriber::init()` before `Runner::new`, the `shotover_proxy` subscriber is not set as the default, because `console_subscriber::init()` has already set the default. So, by using `init`, you are preventing the previous subscriber configuration from being set, changing what events are logged.

`console_subscriber::init()` is intended for use in applications where you don't have other `tracing` `Layer`s you want to use. To compose the `console_subscriber` layer along with other `tracing` code, you should use [`console_subscriber::spawn()`](https://docs.rs/console-subscriber/latest/console_subscriber/fn.spawn.html) instead, and add the returned `Layer` to the subscriber configured by `shotover_proxy::Runner`. See [the documentation for `init`](https://docs.rs/console-subscriber/latest/console_subscriber/fn.init.html#further-customization) for details.

Hope that helps!

**Comment by rukai** [comment]
Ah my confusion came from `console_subscriber::init()` setting up logging to stdout at ERROR level, whereas I assumed it would not configure any logging to stdout and concluded that the subscribers init must be succeeding otherwise where are these ERROR logs coming from.
But I can see this behavior documented so no problems there.

However I am still hitting issues with integrating the console with the existing subscriber:
I successfully ported the existing subscriber to a registry but when I try to add `.with(console_subscriber::spawn()`, I get this error:
![image](https://user-images.githubusercontent.com/5120858/161203221-11dfdbb6-7aaa-4f77-95c9-507602ce0918.png)
I think I cant name that type due to the `impl tracing_subscriber::Layer<Registry>` in there.
Is there a way to store a tracing_subscriber::reload::Handle without naming the full generic type?
