### ISSUE TITLE
TUI messed up on debian

### ISSUE THREAD

**Issue by guerinoni** [tokio-rs/console#339]
### What crate(s) in this repo are involved in the problem?

tokio-console

### What is the issue?

This is what I saw on debian unstable with xfce-terminal.
After this I tried on latest tag and all it's ok.
The SIGWINCH was trapped in right way and the TUI was rendered well only for 1s on resize event.

![image](https://user-images.githubusercontent.com/41150432/165979556-e3810fd2-32e7-444e-985c-893ee1dfdcb7.png)

### How can the bug be reproduced?

Running xfce-terminal in debian is enought.

### Versions

472ff52e6445dd2c103b218d60a4e0cad9a1972e

### Would you like to work on fixing this bug?

maybe

**Comment by hawkw** [comment]
Thanks for the report, this definitely looks wrong.

I notice that it looks like some of the console's own logging seems to have accidentally gotten mixed in with the TUI output. What happens if you re-run with `RUST_LOG=off`?

**Comment by hawkw** [comment]
We should probably change the console so that it never logs to stderr --- the intention was that if you want to get the console's own logging out, you would redirect stderr to a file, but we should probably just not touch stderr/stdout, so that we don't mess up the UI. Instead, we should always either log to a file or to the syslog/system journal (when available).

**Comment by hawkw** [comment]
@guerinoni PR #340 _should_ fix this, mind giving that branch a try?

**Comment by guerinoni** [comment]
Thank you Eliza :) seems working correctly!

**Comment by hawkw** [comment]
great, thanks for confirming!
