### ISSUE TITLE
Please include LICENSE file in the crate

### ISSUE THREAD

**Issue by erickt** [tokio-rs/console#346]
### What problem are you trying to solve?

The `tokio-console` crate does not include the `LICENSE` file. It's easier for us to make sure we're respecting the license if the crate carries the license that goes with the source code, rather than having to refer to the source repository.

### How should the problem be solved?

Would it be possible to include the `LICENSE` file in the `tokio-console` crate, similar to how `tokio` includes it? https://docs.rs/crate/tokio/latest/source/LICENSE.

### Any alternatives you've considered?

None considered.

### How would users interact with this feature?

N/A

### Would you like to work on this feature?

maybe

**Comment by hawkw** [comment]
I was confused for a moment because I was pretty sure there was a `LICENSE` file in the root of the repo...but I realized that what you meant was that it isn't included in the actual crate directories that are published to crates.io (and presumably doesn't show up when using tools like `cargo vendor` etc?). 

We can definitely fix this!

**Comment by erickt** [comment]
Yes exactly! Really appreciate it @hawkw! I think the latest cargo will automatically include `LICENSE*` files upon publish, so I'm pretty sure it'd be automatically picked up next time you publish a crate.
