### ISSUE TITLE
Minimum version may need to be bumped (in documentation)

### ISSUE THREAD

**Issue by arifd** [tokio-rs/console#386]
### What crate(s) in this repo are involved in the problem?

console-subscriber

### What is the issue?

with this in my Cargo.toml
```
tokio = { version = "=1.17.0", features = ["tracing"] }
console-subscriber = "=0.1.8"
```
and `tokio_unstable` in my RUSTFLAGS

Something refuses to build (even after `cargo clean`), with this error:
```
error[E0599]: no method named `unwrap` found for struct `tokio::task::JoinHandle` in the current scope
    --> /home/arif/.cargo/registry/src/github.com-1ecc6299db9ec823/console-subscriber-0.1.8/src/lib.rs:1066:64
     |
1066 |     return tokio::task::Builder::new().name(_name).spawn(task).unwrap();
     |                                                                ^^^^^^ method not found in `tokio::task::JoinHandle<T>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `console-subscriber` due to previous error
```
This was resolved when i bumped `tokio` to `=1.21.2`

This is what the documentation says:
![image](https://user-images.githubusercontent.com/2345750/200862893-0bfda0d0-4c17-4022-ad1f-31aa7d4b35cf.png)

### How can the bug be reproduced?

.

### Logs, error output, etc

.

### Versions

.

### Possible solution

.

### Additional context

.

### Would you like to work on fixing this bug?

maybe

**Comment by hawkw** [comment]
Ah, yeah, that's because the `console-subscriber` crate uses the unstable `task::Builder` API to name the tasks it spawns, and that API changed slightly in Tokio 1.21.0 (`Builder::spawn` was made fallible): https://github.com/tokio-rs/tokio/blob/master/tokio/CHANGELOG.md#unstable

We should update `console-subscriber`'s `tokio` dependency here: https://github.com/tokio-rs/console/blob/06531a91af5b3922e615a0ce3578ebf4ae5c9059/console-subscriber/Cargo.toml#L35 as well as the documentation.

Thanks for the report, good catch!
