### ISSUE TITLE
Standardize on span naming

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/console#41]
The prototype currently just looks for a span named `tokio::task::spawn`, but if want to work for any "runtime"-like thingy, we probably should have a more generic name. It still needs to be unique enough that a user would be very unlikely to create a span with the same name.

Besides task spawning, we also need to do this for [wakers](#37) and [resources](#39) too.

**Comment by hawkw** [comment]
I think we should probably care about _just_ a standardized span name, rather than a standardized span name and `tracing` target. I think it would be good to allow runtimes to have the target differ,

For example, @nikomatsakis mentioned wanting to instrument `rayon` with the console. So, if you're using `tokio` *and* `rayon` in the same program, we could distinguish between spans named `spawn` with the `tokio::task` target, and spans named `spawn` with the `rayon` target. Although, on the other hand, we could use a custom target but also display the module path.

The other thing is whether `spawn` is the correct name. We may want to use something less generic, to ensure that people don't accidentally create spans with the `spawn` name that aren't actually supposed to correspond to tasks.

Perhaps one option would be to require overridden targets beginning with `console`, *as well* as the `spawn` span naming? I dunno, just throwing out ideas here.

**Comment by carllerche** [comment]
To help avoid name collision, we can probably include a prefix. e.g. "runtime.spawn".

**Comment by hawkw** [comment]
+1 for @carllerche's suggestion of `runtime.`, that seems like a good naming convention to indicate that the span is provided by the runtime's instrumentation rather than user code, and avoid colliding with user spans, but without tying the naming scheme to an individual runtime implementation.

**Comment by carllerche** [comment]
Ref: tokio-rs/tokio#3954 with regards to figuring out how to name resource spans. My guess is we need a "kind" annotation to identify resource spans vs. operation spans as well.

**Comment by hawkw** [comment]
I believe #68 completed the console side work for this. We still need to update tokio to use the new naming scheme, though.
