### ISSUE TITLE
Pretty task IDs

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/console#61]
Currently, task IDs can be big:

![](https://user-images.githubusercontent.com/4391506/125077235-8affcb80-e0c9-11eb-89ab-3b269c1a9bbc.png)

We could use an `AtomicUsize` to generate incrementing task IDs that start off shorter.

**Comment by hawkw** [comment]
Right now, we just reuse the `tracing` span IDs as task IDs. Because these are actually slab indices that include an offset, generation, and thread ID, they are often long. 

We could probably just have the console-subscriber's `Aggregator` task store a `HashMap` of `tracing::span::Id` -> pretty IDs, and generate the pretty IDs by incrementing a counter. We wouldn't even need to use an `AtomicUsize` for the counter, since the `Aggregator` task is an actor that owns all the mutable state. Putting the hash map in the aggregator task would mean that the subscriber layer doesn't need to know about the `tracing` ID -> pretty ID mapping, so the hashmap doesn't need to be shared --- we don't need to introduce a mutex for the mapping.

OTTOH, it is currently possible to reconstruct the thread ID on which a span was created from the `tracing` span IDs, which wouldn't be possible if we replaced them with counter-based IDs. But, we're not currently doing anything interesting with that data...and, it would be tightly coupled with the `tracing-subscriber` `Registry` type, so it wouldn't play as nice with other subscribers...

**Comment by oguzbilgener** [comment]
I'd be happy to take this one on as well. It seems clear enough.

Are there any other requirements or ideas based on the vision for console that would require the implementation to be more flexible than what @hawkw described above with the `tracing::span::Id` -> pretty IDs mapping?

**Comment by hawkw** [comment]
@oguzbilgener not that I'm aware of, I think this ought to be fairly straightforward. If we end up needing anything else, we can always change this later.

Let me know if you have any questions?

**Comment by oguzbilgener** [comment]
I'm guessing we want something like this? Plain, decimal, incrementing u64 task IDs:

![Screenshot from 2021-07-23 21-54-14](https://user-images.githubusercontent.com/1333721/126854387-df3d91a7-3996-4f9e-b661-ba2fdb278cc4.png)

**Comment by hawkw** [comment]
After merging #75, this definitely looks much nicer: 
![image](https://user-images.githubusercontent.com/2796466/128055830-5525c257-9e59-4a36-9a8f-e6fb6d87ecda.png)

**Comment by hawkw** [comment]
I do wonder if maybe we want the task IDs to start at 1 rather than at 0, but :woman_shrugging:
