### ISSUE TITLE
wish: more distinguished units on numbers

### ISSUE THREAD

**Issue by pnkfelix** [tokio-rs/console#71]
Its great that we're using units on our values so that we don't have to fill up too many columns when people will only want 2 or 3 sig figs of info per value.

But: I worry that its too easy to overlook the difference when you see "21ms 34μs" in a column or even "21s 3ms"

What are good ways to mitigate this? Main ideas I can think of:

1. When sorting by column, add blank lines between rows when the unit changes. (The main drawbacks here: it wastes space on aforementioned blank lines. Also, it only works for sorting by the column where confusion occurs, which means people can still overlook it when it happens in an unsorted column.)
2. Use colors to distinguish the units. I.e. color `s` with red, `ms` with yellow, `μs` with green.

**Comment by hawkw** [comment]
Color-coding definitely seems like a good idea. I think it's very important that we never *rely* on colors to communicate anything, so that all the information is still available on terminals that don't support colors; however, it's a great idea to use colors in cases like this, where the information is *present* regardless but the color-coding makes it easier to visually distinguish. I wonder if we should also bold the units so that they stand out better?

I'm less *sure* about the idea of adding blank lines, but I think it's definitely worth trying it out and seeing how it looks? I feel like it's actually more important to be able to distinguish different units in cases where the column _isn't_ the sorting key, since they'll all be mixed together, but anything that makes the data easier to read is definitely worth trying!

**Comment by hawkw** [comment]
Okay, I threw together a quick draft of coloring durations based on their units: 
![image](https://user-images.githubusercontent.com/2796466/126686509-e5fe37f7-82e7-422e-a486-c8d60e97ed6a.png)

**Comment by seanmonstar** [comment]
@pnkfelix Eliza added some colors for different units in #72 (and see picture), seem good enough to mark this done?

**Comment by hawkw** [comment]
> @pnkfelix Eliza added some colors for different units in #72 (and see picture), seem good enough to mark this done?

I left it open at the time since i thought we might also want to investigate adding blank line separators when sorting tables... but i'm still on the fence about whether that's actually a good idea. 

We can close this and look into that idea separately.
