### ISSUE TITLE
Need some way to enable "tokio=trace" filter for the console Layer only

### ISSUE THREAD

**Issue by sbrocket** [tokio-rs/console#76]
First off...this is super cool, thanks for creating it!

The requirement to enable trace-level events for tokio to use this console means that other layers also receive those events, which makes a fmt Layer pretty unusable without out-of-band filtering.

Per https://github.com/tokio-rs/tracing/issues/302, it looks like per-layer filtering does not yet exist. Before I'd discovered that I'd tried combining separate `EnvFilter`s with a fmt Layer and a console Layer using `Layer::and_then`, but this clearly doesn't work as expected.

Maybe there's another workaround I haven't thought of?

**Comment by hawkw** [comment]
For now, the best solution is to use [`MakeWriterExt`](https://docs.rs/tracing-subscriber/0.2.19/tracing_subscriber/fmt/writer/trait.MakeWriterExt.html#) to add an _output filter_ that disables `tokio=trace` to the writer used by your `fmt` layer. This will prevent it from printing events emitted by Tokio, but still allows the subscriber to record them, so that they can be used for the console. 

For example, you could write
```rust
use tracing_subscriber::prelude::*;

let fmt = tracing_subscriber::fmt::layer()
    .with_writer(std::io::stdout
        // Don't print logs for events with the `tokio` target.
        .with_filter(|meta| meta.target() != "tokio")
    );
    // ... plus any additional `fmt` configurations you may want...

console_subscriber::build()
    .with(fmt)
    .init();
```

The one caveat here is that the _spans_ used by the console will not be filtered out when printing events that _are_ enabled by other filter settings, so those spans will be shown as part of the span context for those events. A stopgap solution for until we have proper, generic per-layer filtering could be to add a similar form of filtering to `tracing-subscriber::fmt` when formatting span contexts, so that the `fmt` layer could skip over spans that don't match a predicate as it builds a context. 

See also https://github.com/tokio-rs/console/pull/64#issuecomment-879441993

**Comment by hawkw** [comment]
upstream change tokio-rs/tracing#1523 should fix this in a somewhat nicer way
